version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'

    [blocks.segments.properties]
    style = 'full'

  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  foreground = 'magenta'
  background = 'transparent'
  template = "〉"
