# Alacritty Config
[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
padding.x = 5
padding.y = 0

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "Hack Nerd Font Mono"
